apiVersion: v2
name: crypt-pit
description: A Helm chart for Crypt-Pit password generator
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - password-generator
  - web-app
  - static-site
home: https://github.com/skravops-cmd/crypt-pit
sources:
  - https://github.com/skravops-cmd/crypt-pit
maintainers:
  - name: skravops-cmd