apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app: crypt-pit
    managed-by: kustomize
  name: crypt-pit
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`crypt.skravops.xyz`)
    services:
    - name: crypt-pit
      port: 80
